/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as PrdsRouteImport } from './routes/prds'
import { Route as HpanelRouteImport } from './routes/hpanel'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HpanelIndexRouteImport } from './routes/hpanel.index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as SkillSkillIdRouteImport } from './routes/skill.$skillId'
import { Route as PrdSlugRouteImport } from './routes/prd.$slug'
import { Route as HpanelSubmissionsRouteImport } from './routes/hpanel.submissions'
import { Route as HpanelSkillsRouteImport } from './routes/hpanel.skills'
import { Route as HpanelSettingsRouteImport } from './routes/hpanel.settings'
import { Route as HpanelPrdsRouteImport } from './routes/hpanel.prds'
import { Route as HpanelPrdCategoriesRouteImport } from './routes/hpanel.prd-categories'
import { Route as HpanelImportRouteImport } from './routes/hpanel.import'
import { Route as HpanelDocsRouteImport } from './routes/hpanel.docs'
import { Route as HpanelCategoriesRouteImport } from './routes/hpanel.categories'
import { Route as HpanelAddRouteImport } from './routes/hpanel.add'
import { Route as DocsWhatAreSkillsRouteImport } from './routes/docs.what-are-skills'
import { Route as DocsSpecificationRouteImport } from './routes/docs.specification'
import { Route as DocsIntegrateRouteImport } from './routes/docs.integrate'
import { Route as DocsCreateRouteImport } from './routes/docs.create'

const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const PrdsRoute = PrdsRouteImport.update({
  id: '/prds',
  path: '/prds',
  getParentRoute: () => rootRouteImport,
} as any)
const HpanelRoute = HpanelRouteImport.update({
  id: '/hpanel',
  path: '/hpanel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HpanelIndexRoute = HpanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HpanelRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillSkillIdRoute = SkillSkillIdRouteImport.update({
  id: '/skill/$skillId',
  path: '/skill/$skillId',
  getParentRoute: () => rootRouteImport,
} as any)
const PrdSlugRoute = PrdSlugRouteImport.update({
  id: '/prd/$slug',
  path: '/prd/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HpanelSubmissionsRoute = HpanelSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => HpanelRoute,
} as any)
const HpanelSkillsRoute = HpanelSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => HpanelRoute,
} as any)
const HpanelSettingsRoute = HpanelSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HpanelRoute,
} as any)
const HpanelPrdsRoute = HpanelPrdsRouteImport.update({
  id: '/prds',
  path: '/prds',
  getParentRoute: () => HpanelRoute,
} as any)
const HpanelPrdCategoriesRoute = HpanelPrdCategoriesRouteImport.update({
  id: '/prd-categories',
  path: '/prd-categories',
  getParentRoute: () => HpanelRoute,
} as any)
const HpanelImportRoute = HpanelImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => HpanelRoute,
} as any)
const HpanelDocsRoute = HpanelDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => HpanelRoute,
} as any)
const HpanelCategoriesRoute = HpanelCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => HpanelRoute,
} as any)
const HpanelAddRoute = HpanelAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => HpanelRoute,
} as any)
const DocsWhatAreSkillsRoute = DocsWhatAreSkillsRouteImport.update({
  id: '/docs/what-are-skills',
  path: '/docs/what-are-skills',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSpecificationRoute = DocsSpecificationRouteImport.update({
  id: '/docs/specification',
  path: '/docs/specification',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIntegrateRoute = DocsIntegrateRouteImport.update({
  id: '/docs/integrate',
  path: '/docs/integrate',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCreateRoute = DocsCreateRouteImport.update({
  id: '/docs/create',
  path: '/docs/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hpanel': typeof HpanelRouteWithChildren
  '/prds': typeof PrdsRoute
  '/skills': typeof SkillsRoute
  '/submit': typeof SubmitRoute
  '/docs/create': typeof DocsCreateRoute
  '/docs/integrate': typeof DocsIntegrateRoute
  '/docs/specification': typeof DocsSpecificationRoute
  '/docs/what-are-skills': typeof DocsWhatAreSkillsRoute
  '/hpanel/add': typeof HpanelAddRoute
  '/hpanel/categories': typeof HpanelCategoriesRoute
  '/hpanel/docs': typeof HpanelDocsRoute
  '/hpanel/import': typeof HpanelImportRoute
  '/hpanel/prd-categories': typeof HpanelPrdCategoriesRoute
  '/hpanel/prds': typeof HpanelPrdsRoute
  '/hpanel/settings': typeof HpanelSettingsRoute
  '/hpanel/skills': typeof HpanelSkillsRoute
  '/hpanel/submissions': typeof HpanelSubmissionsRoute
  '/prd/$slug': typeof PrdSlugRoute
  '/skill/$skillId': typeof SkillSkillIdRoute
  '/docs/': typeof DocsIndexRoute
  '/hpanel/': typeof HpanelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prds': typeof PrdsRoute
  '/skills': typeof SkillsRoute
  '/submit': typeof SubmitRoute
  '/docs/create': typeof DocsCreateRoute
  '/docs/integrate': typeof DocsIntegrateRoute
  '/docs/specification': typeof DocsSpecificationRoute
  '/docs/what-are-skills': typeof DocsWhatAreSkillsRoute
  '/hpanel/add': typeof HpanelAddRoute
  '/hpanel/categories': typeof HpanelCategoriesRoute
  '/hpanel/docs': typeof HpanelDocsRoute
  '/hpanel/import': typeof HpanelImportRoute
  '/hpanel/prd-categories': typeof HpanelPrdCategoriesRoute
  '/hpanel/prds': typeof HpanelPrdsRoute
  '/hpanel/settings': typeof HpanelSettingsRoute
  '/hpanel/skills': typeof HpanelSkillsRoute
  '/hpanel/submissions': typeof HpanelSubmissionsRoute
  '/prd/$slug': typeof PrdSlugRoute
  '/skill/$skillId': typeof SkillSkillIdRoute
  '/docs': typeof DocsIndexRoute
  '/hpanel': typeof HpanelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hpanel': typeof HpanelRouteWithChildren
  '/prds': typeof PrdsRoute
  '/skills': typeof SkillsRoute
  '/submit': typeof SubmitRoute
  '/docs/create': typeof DocsCreateRoute
  '/docs/integrate': typeof DocsIntegrateRoute
  '/docs/specification': typeof DocsSpecificationRoute
  '/docs/what-are-skills': typeof DocsWhatAreSkillsRoute
  '/hpanel/add': typeof HpanelAddRoute
  '/hpanel/categories': typeof HpanelCategoriesRoute
  '/hpanel/docs': typeof HpanelDocsRoute
  '/hpanel/import': typeof HpanelImportRoute
  '/hpanel/prd-categories': typeof HpanelPrdCategoriesRoute
  '/hpanel/prds': typeof HpanelPrdsRoute
  '/hpanel/settings': typeof HpanelSettingsRoute
  '/hpanel/skills': typeof HpanelSkillsRoute
  '/hpanel/submissions': typeof HpanelSubmissionsRoute
  '/prd/$slug': typeof PrdSlugRoute
  '/skill/$skillId': typeof SkillSkillIdRoute
  '/docs/': typeof DocsIndexRoute
  '/hpanel/': typeof HpanelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hpanel'
    | '/prds'
    | '/skills'
    | '/submit'
    | '/docs/create'
    | '/docs/integrate'
    | '/docs/specification'
    | '/docs/what-are-skills'
    | '/hpanel/add'
    | '/hpanel/categories'
    | '/hpanel/docs'
    | '/hpanel/import'
    | '/hpanel/prd-categories'
    | '/hpanel/prds'
    | '/hpanel/settings'
    | '/hpanel/skills'
    | '/hpanel/submissions'
    | '/prd/$slug'
    | '/skill/$skillId'
    | '/docs/'
    | '/hpanel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/prds'
    | '/skills'
    | '/submit'
    | '/docs/create'
    | '/docs/integrate'
    | '/docs/specification'
    | '/docs/what-are-skills'
    | '/hpanel/add'
    | '/hpanel/categories'
    | '/hpanel/docs'
    | '/hpanel/import'
    | '/hpanel/prd-categories'
    | '/hpanel/prds'
    | '/hpanel/settings'
    | '/hpanel/skills'
    | '/hpanel/submissions'
    | '/prd/$slug'
    | '/skill/$skillId'
    | '/docs'
    | '/hpanel'
  id:
    | '__root__'
    | '/'
    | '/hpanel'
    | '/prds'
    | '/skills'
    | '/submit'
    | '/docs/create'
    | '/docs/integrate'
    | '/docs/specification'
    | '/docs/what-are-skills'
    | '/hpanel/add'
    | '/hpanel/categories'
    | '/hpanel/docs'
    | '/hpanel/import'
    | '/hpanel/prd-categories'
    | '/hpanel/prds'
    | '/hpanel/settings'
    | '/hpanel/skills'
    | '/hpanel/submissions'
    | '/prd/$slug'
    | '/skill/$skillId'
    | '/docs/'
    | '/hpanel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HpanelRoute: typeof HpanelRouteWithChildren
  PrdsRoute: typeof PrdsRoute
  SkillsRoute: typeof SkillsRoute
  SubmitRoute: typeof SubmitRoute
  DocsCreateRoute: typeof DocsCreateRoute
  DocsIntegrateRoute: typeof DocsIntegrateRoute
  DocsSpecificationRoute: typeof DocsSpecificationRoute
  DocsWhatAreSkillsRoute: typeof DocsWhatAreSkillsRoute
  PrdSlugRoute: typeof PrdSlugRoute
  SkillSkillIdRoute: typeof SkillSkillIdRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prds': {
      id: '/prds'
      path: '/prds'
      fullPath: '/prds'
      preLoaderRoute: typeof PrdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hpanel': {
      id: '/hpanel'
      path: '/hpanel'
      fullPath: '/hpanel'
      preLoaderRoute: typeof HpanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hpanel/': {
      id: '/hpanel/'
      path: '/'
      fullPath: '/hpanel/'
      preLoaderRoute: typeof HpanelIndexRouteImport
      parentRoute: typeof HpanelRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill/$skillId': {
      id: '/skill/$skillId'
      path: '/skill/$skillId'
      fullPath: '/skill/$skillId'
      preLoaderRoute: typeof SkillSkillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prd/$slug': {
      id: '/prd/$slug'
      path: '/prd/$slug'
      fullPath: '/prd/$slug'
      preLoaderRoute: typeof PrdSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hpanel/submissions': {
      id: '/hpanel/submissions'
      path: '/submissions'
      fullPath: '/hpanel/submissions'
      preLoaderRoute: typeof HpanelSubmissionsRouteImport
      parentRoute: typeof HpanelRoute
    }
    '/hpanel/skills': {
      id: '/hpanel/skills'
      path: '/skills'
      fullPath: '/hpanel/skills'
      preLoaderRoute: typeof HpanelSkillsRouteImport
      parentRoute: typeof HpanelRoute
    }
    '/hpanel/settings': {
      id: '/hpanel/settings'
      path: '/settings'
      fullPath: '/hpanel/settings'
      preLoaderRoute: typeof HpanelSettingsRouteImport
      parentRoute: typeof HpanelRoute
    }
    '/hpanel/prds': {
      id: '/hpanel/prds'
      path: '/prds'
      fullPath: '/hpanel/prds'
      preLoaderRoute: typeof HpanelPrdsRouteImport
      parentRoute: typeof HpanelRoute
    }
    '/hpanel/prd-categories': {
      id: '/hpanel/prd-categories'
      path: '/prd-categories'
      fullPath: '/hpanel/prd-categories'
      preLoaderRoute: typeof HpanelPrdCategoriesRouteImport
      parentRoute: typeof HpanelRoute
    }
    '/hpanel/import': {
      id: '/hpanel/import'
      path: '/import'
      fullPath: '/hpanel/import'
      preLoaderRoute: typeof HpanelImportRouteImport
      parentRoute: typeof HpanelRoute
    }
    '/hpanel/docs': {
      id: '/hpanel/docs'
      path: '/docs'
      fullPath: '/hpanel/docs'
      preLoaderRoute: typeof HpanelDocsRouteImport
      parentRoute: typeof HpanelRoute
    }
    '/hpanel/categories': {
      id: '/hpanel/categories'
      path: '/categories'
      fullPath: '/hpanel/categories'
      preLoaderRoute: typeof HpanelCategoriesRouteImport
      parentRoute: typeof HpanelRoute
    }
    '/hpanel/add': {
      id: '/hpanel/add'
      path: '/add'
      fullPath: '/hpanel/add'
      preLoaderRoute: typeof HpanelAddRouteImport
      parentRoute: typeof HpanelRoute
    }
    '/docs/what-are-skills': {
      id: '/docs/what-are-skills'
      path: '/docs/what-are-skills'
      fullPath: '/docs/what-are-skills'
      preLoaderRoute: typeof DocsWhatAreSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/specification': {
      id: '/docs/specification'
      path: '/docs/specification'
      fullPath: '/docs/specification'
      preLoaderRoute: typeof DocsSpecificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/integrate': {
      id: '/docs/integrate'
      path: '/docs/integrate'
      fullPath: '/docs/integrate'
      preLoaderRoute: typeof DocsIntegrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/create': {
      id: '/docs/create'
      path: '/docs/create'
      fullPath: '/docs/create'
      preLoaderRoute: typeof DocsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HpanelRouteChildren {
  HpanelAddRoute: typeof HpanelAddRoute
  HpanelCategoriesRoute: typeof HpanelCategoriesRoute
  HpanelDocsRoute: typeof HpanelDocsRoute
  HpanelImportRoute: typeof HpanelImportRoute
  HpanelPrdCategoriesRoute: typeof HpanelPrdCategoriesRoute
  HpanelPrdsRoute: typeof HpanelPrdsRoute
  HpanelSettingsRoute: typeof HpanelSettingsRoute
  HpanelSkillsRoute: typeof HpanelSkillsRoute
  HpanelSubmissionsRoute: typeof HpanelSubmissionsRoute
  HpanelIndexRoute: typeof HpanelIndexRoute
}

const HpanelRouteChildren: HpanelRouteChildren = {
  HpanelAddRoute: HpanelAddRoute,
  HpanelCategoriesRoute: HpanelCategoriesRoute,
  HpanelDocsRoute: HpanelDocsRoute,
  HpanelImportRoute: HpanelImportRoute,
  HpanelPrdCategoriesRoute: HpanelPrdCategoriesRoute,
  HpanelPrdsRoute: HpanelPrdsRoute,
  HpanelSettingsRoute: HpanelSettingsRoute,
  HpanelSkillsRoute: HpanelSkillsRoute,
  HpanelSubmissionsRoute: HpanelSubmissionsRoute,
  HpanelIndexRoute: HpanelIndexRoute,
}

const HpanelRouteWithChildren =
  HpanelRoute._addFileChildren(HpanelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HpanelRoute: HpanelRouteWithChildren,
  PrdsRoute: PrdsRoute,
  SkillsRoute: SkillsRoute,
  SubmitRoute: SubmitRoute,
  DocsCreateRoute: DocsCreateRoute,
  DocsIntegrateRoute: DocsIntegrateRoute,
  DocsSpecificationRoute: DocsSpecificationRoute,
  DocsWhatAreSkillsRoute: DocsWhatAreSkillsRoute,
  PrdSlugRoute: PrdSlugRoute,
  SkillSkillIdRoute: SkillSkillIdRoute,
  DocsIndexRoute: DocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
