-- Import PRDs directly into the database
INSERT OR REPLACE INTO prds (id, slug, name, description, category, tags, author, version, file_path, view_count, download_count, like_count, status, created_at, updated_at) VALUES
('e-commerce-platform-spec', 'e-commerce-platform-spec', 'E-Commerce Platform PRD', 'A comprehensive PRD for a modern e-commerce platform with cart management, checkout, and order tracking.', 'business', '["ecommerce", "retail", "payments", "cart"]', 'Ralphy Team', '1.1', '/specs/business/e-commerce-platform-spec.md', 0, 0, 0, 'published', datetime('now'), datetime('now')),
('social-fitness-spec', 'social-fitness-spec', 'Social Fitness App PRD', 'A fitness and wellness app with social features, workout tracking, and community challenges.', 'consumer', '["fitness", "social", "health", "wellness"]', 'Ralphy Team', '1.1', '/specs/consumer/social-fitness-spec.md', 0, 0, 0, 'published', datetime('now'), datetime('now')),
('design-collab-spec', 'design-collab-spec', 'Design Collaboration Platform PRD', 'A real-time design collaboration platform for teams with versioning and feedback tools.', 'creative', '["design", "collaboration", "creative", "figma-like"]', 'Ralphy Team', '1.1', '/specs/creative/design-collab-spec.md', 0, 0, 0, 'published', datetime('now'), datetime('now')),
('api-gateway-spec', 'api-gateway-spec', 'Vortex API Gateway PRD', 'A cloud-native API gateway with authentication, rate limiting, and observability for microservices.', 'developer', '["api", "gateway", "microservices", "backend"]', 'Ralphy Team', '1.1', '/specs/developer/api-gateway-spec.md', 0, 0, 0, 'published', datetime('now'), datetime('now')),
('lms-spec', 'lms-spec', 'Learning Management System PRD', 'An LMS for online courses with progress tracking, assessments, and certifications.', 'education', '["education", "lms", "courses", "learning"]', 'Ralphy Team', '1.1', '/specs/education/lms-spec.md', 0, 0, 0, 'published', datetime('now'), datetime('now')),
('telemedicine-app-spec', 'telemedicine-app-spec', 'Telemedicine App PRD', 'A telemedicine platform for virtual consultations, prescriptions, and health records.', 'health', '["health", "telemedicine", "medical", "healthcare"]', 'Ralphy Team', '1.1', '/specs/health/telemedicine-app-spec.md', 0, 0, 0, 'published', datetime('now'), datetime('now')),
('inventory-tracking-spec', 'inventory-tracking-spec', 'Inventory Tracking System PRD', 'An inventory and warehouse management system with barcode scanning and analytics.', 'operations', '["inventory", "warehouse", "operations", "logistics"]', 'Ralphy Team', '1.1', '/specs/operations/inventory-tracking-spec.md', 0, 0, 0, 'published', datetime('now'), datetime('now')),
('community-event-spec', 'community-event-spec', 'Community Event Platform PRD', 'A platform for organizing local events, meetups, and community gatherings.', 'other', '["events", "community", "social", "meetups"]', 'Ralphy Team', '1.1', '/specs/other/community-event-spec.md', 0, 0, 0, 'published', datetime('now'), datetime('now')),
('pm-tool-spec', 'pm-tool-spec', 'Project Management Tool PRD', 'A project management tool with task boards, time tracking, and team collaboration.', 'productivity', '["project-management", "productivity", "tasks", "collaboration"]', 'Ralphy Team', '1.1', '/specs/productivity/pm-tool-spec.md', 0, 0, 0, 'published', datetime('now'), datetime('now'));
